apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: snvu4oe8u-nodejs 
  janus-idp.io/tekton: snvu4oe8u-nodejs
  backstage.io/kubernetes-id: snvu4oe8u-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: snvu4oe8u-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  